DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT Now()
);
CREATE TABLE expenses (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  expense_type VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  amount INTEGER NOT NULL DEFAULT 0,
  expense_date VARCHAR(255) NOT NULL,
  added_at TIMESTAMPTZ DEFAULT Now()
);